module.exports = {
  ab: { name: "Abkhazian", nativeName: "аҧсуа" },
  aa: { name: "Afar", nativeName: "Afaraf" },
  af: { name: "Afrikaans", nativeName: "Afrikaans" },
  ak: { name: "Akan", nativeName: "Akan" },
  sq: { name: "Albanian", nativeName: "Shqip" },
  am: { name: "Amharic", nativeName: "አማርኛ" },
  ar: { name: "Arabic", nativeName: "العربية" },
  an: { name: "Aragonese", nativeName: "Aragonés" },
  hy: { name: "Armenian", nativeName: "Հայերեն" },
  as: { name: "Assamese", nativeName: "অসমীয়া" },
  av: { name: "Avaric", nativeName: "авар мацӀ, магӀарул мацӀ" },
  ae: { name: "Avestan", nativeName: "avesta" },
  ay: { name: "Aymara", nativeName: "aymar aru" },
  az: { name: "Azerbaijani", nativeName: "azərbaycan dili" },
  bm: { name: "Bambara", nativeName: "bamanankan" },
  ba: { name: "Bashkir", nativeName: "башҡорт теле" },
  eu: { name: "Basque", nativeName: "euskara, euskera" },
  be: { name: "Belarusian", nativeName: "Беларуская" },
  bn: { name: "Bengali", nativeName: "বাংলা" },
  bh: { name: "Bihari", nativeName: "भोजपुरी" },
  bi: { name: "Bislama", nativeName: "Bislama" },
  bs: { name: "Bosnian", nativeName: "bosanski jezik" },
  br: { name: "Breton", nativeName: "brezhoneg" },
  bg: { name: "Bulgarian", nativeName: "български език" },
  my: { name: "Burmese", nativeName: "ဗမာစာ" },
  ca: { name: "Catalan; Valencian", nativeName: "Català" },
  ch: { name: "Chamorro", nativeName: "Chamoru" },
  ce: { name: "Chechen", nativeName: "нохчийн мотт" },
  ny: { name: "Chichewa; Chewa; Nyanja", nativeName: "chiCheŵa, chinyanja" },
  zh: { name: "Chinese", nativeName: "中文 (Zhōngwén)" },
  "zh-Hans": { name: "Chinese (Simplified)", nativeName: "汉语", alterCode: "zh-cn" },
  "zh-Hant": { name: "Chinese (Traditional)", nativeName: "漢語", alterCode: "zh-tw" },
  dv: { name: "Divehi; Dhivehi; Maldivian;", nativeName: "ދިވެހި" },
  mi: { name: "Māori", nativeName: "te reo Māori" },
  qu: { name: "Quechua", nativeName: "Runa Simi, Kichwa" },
  sa: { name: "Sanskrit (Saṁskṛta)", nativeName: "संस्कृतम्" },
  se: { name: "Northern Sami", nativeName: "Davvisámegiella" },
  ht: { name: "Haitian; Haitian Creole", nativeName: "Kreyòl ayisyen" },
  hr: { name: "Croatian", nativeName: "hrvatski" },
  cs: { name: "Czech", nativeName: "česky, čeština" },
  da: { name: "Danish", nativeName: "dansk" },
  nl: { name: "Dutch", nativeName: "Nederlands, Vlaams" },
  en: { name: "English", nativeName: "English" },
  eo: { name: "Esperanto", nativeName: "Esperanto" },
  et: { name: "Estonian", nativeName: "eesti, eesti keel" },
  fo: { name: "Faroese", nativeName: "føroyskt" },
  fi: { name: "Finnish", nativeName: "suomi, suomen kieli" },
  fr: { name: "French", nativeName: "français, langue française" },
  "fr-CA": { name: "French (Canada)", nativeName: "Français (Canada)" },
  gl: { name: "Galician", nativeName: "Galego" },
  ka: { name: "Georgian", nativeName: "ქართული" },
  de: { name: "German", nativeName: "Deutsch" },
  el: { name: "Greek, Modern", nativeName: "Ελληνικά" },
  gu: { name: "Gujarati", nativeName: "ગુજરાતી" },
  ha: { name: "Hausa", nativeName: "Hausa, هَوُسَ" },
  he: { name: "Hebrew (modern)", nativeName: "עברית" },
  hi: { name: "Hindi", nativeName: "हिन्दी, हिंदी" },
  hu: { name: "Hungarian", nativeName: "Magyar" },
  is: { name: "Icelandic", nativeName: "Íslenska" },
  ig: { name: "Igbo", nativeName: "Asụsụ Igbo" },
  id: { name: "Indonesian", nativeName: "Bahasa Indonesia" },
  ga: { name: "Irish", nativeName: "Gaeilge" },
  it: { name: "Italian", nativeName: "Italiano" },
  ja: { name: "Japanese", nativeName: "日本語" },
  kn: { name: "Kannada", nativeName: "ಕನ್ನಡ" },
  kk: { name: "Kazakh", nativeName: "Қазақ тілі" },
  km: { name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  ko: { name: "Korean", nativeName: "한국어 (韓國語)" },
  ku: { name: "Kurdish", nativeName: "Kurdî, كوردی‎" },
  ky: { name: "Kirghiz, Kyrgyz", nativeName: "кыргыз тили" },
  lo: { name: "Lao", nativeName: "ພາສາລາວ" },
  la: { name: "Latin", nativeName: "latine, lingua latina" },
  lv: { name: "Latvian", nativeName: "latviešu valoda" },
  lt: { name: "Lithuanian", nativeName: "lietuvių kalba" },
  lb: { name: "Luxembourgish, Letzeburgesch", nativeName: "Lëtzebuergesch" },
  mk: { name: "Macedonian", nativeName: "македонски јазик" },
  mg: { name: "Malagasy", nativeName: "Malagasy fiteny" },
  ms: { name: "Malay", nativeName: "bahasa Melayu, بهاس ملايو‎" },
  ml: { name: "Malayalam", nativeName: "മലയാളം" },
  mt: { name: "Maltese", nativeName: "Malti" },
  mr: { name: "Marathi (Marāṭhī)", nativeName: "मराठी" },
  mn: { name: "Mongolian", nativeName: "монгол" },
  ne: { name: "Nepali", nativeName: "नेपाली" },
  no: { name: "Norwegian", nativeName: "Norsk" },
  nb: { name: "Norwegian Bokmål", nativeName: "Norsk bokmål" },
  nn: { name: "Norwegian Nynorsk", nativeName: "Norsk nynorsk" },
  oc: { name: "Occitan", nativeName: "Occitan" },
  ps: { name: "Pashto, Pushto", nativeName: "پښتو" },
  fa: { name: "Persian", nativeName: "فارسی" },
  pl: { name: "Polish", nativeName: "polski" },
  pt: { name: "Portuguese", nativeName: "Português" },
  "pt-BR": { name: "Portuguese (Brazil)", nativeName: "Português (Brasil)" },
  pa: { name: "Panjabi, Punjabi", nativeName: "ਪੰਜਾਬੀ, پنجابی‎" },
  ro: { name: "Romanian, Moldavian, Moldovan", nativeName: "română" },
  ru: { name: "Russian", nativeName: "русский язык" },
  sc: { name: "Sardinian", nativeName: "sardu" },
  sr: { name: "Serbian", nativeName: "српски језик" },
  si: { name: "Sinhala, Sinhalese", nativeName: "සිංහල" },
  sk: { name: "Slovak", nativeName: "slovenčina" },
  sl: { name: "Slovene", nativeName: "slovenščina" },
  so: { name: "Somali", nativeName: "Soomaaliga, af Soomaali" },
  es: { name: "Spanish; Castilian", nativeName: "español, castellano" },
  sw: { name: "Swahili", nativeName: "Kiswahili" },
  sv: { name: "Swedish", nativeName: "svenska" },
  tl: { name: "Tagalog", nativeName: "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔" },
  tg: { name: "Tajik", nativeName: "тоҷикӣ, toğikī, تاجیکی‎" },
  ta: { name: "Tamil", nativeName: "தமிழ்" },
  tt: { name: "Tatar", nativeName: "татарча, tatarça, تاتارچا‎" },
  te: { name: "Telugu", nativeName: "తెలుగు" },
  th: { name: "Thai", nativeName: "ไทย" },
  bo: { name: "Tibetan Standard, Tibetan, Central", nativeName: "བོད་ཡིག" },
  tr: { name: "Turkish", nativeName: "Türkçe" },
  tk: { name: "Turkmen", nativeName: "Türkmen, Түркмен" },
  uk: { name: "Ukrainian", nativeName: "українська" },
  ur: { name: "Urdu", nativeName: "اردو" },
  ug: { name: "Uighur, Uyghur", nativeName: "Uyƣurqə, ئۇيغۇرچە‎" },
  uz: { name: "Uzbek", nativeName: "zbek, Ўзбек, أۇزبېك‎" },
  vi: { name: "Vietnamese", nativeName: "Tiếng Việt" },
};
